- dataSource: UpdateAttendeeLambdaDataSource
  name: InvokeUpdateAttendeeLambdaDataSource
  request: default-invoke-lambda.req.vtl
  response: default-invoke-lambda.res.vtl
- dataSource: FileUploadLambdaDataSource
  name: InvokeFileUploadLambdaDataSource
  request: default-invoke-lambda.req.vtl
  response: default-invoke-lambda.res.vtl
- dataSource: NumberOfUnreadMessagesLambdaDataSource
  name: InvokeNumberOfUnreadMessagesLambdaDataSource
  request: default-invoke-lambda.req.vtl
  response: default-invoke-lambda.res.vtl
- dataSource: ResolveMatchesLambdaDataSource
  name: InvokeResolveMatchesLambdaDataSource
  request: default-invoke-lambda.req.vtl
  response: default-invoke-lambda.res.vtl
- dataSource: CreateAttendeeLambdaDataSource
  name: InvokeCreateAttendeeLambdaDataSource
  request: default-invoke-lambda.req.vtl
  response: default-invoke-lambda.res.vtl
- dataSource: UpdateCandidateLambdaDataSource
  name: InvokeUpdateCandidateLambdaDataSource
  request: default-invoke-lambda.req.vtl
  response: default-invoke-lambda.res.vtl
- dataSource: ResolveChatsLambdaDataSource
  name: InvokeResolveChatsLambdaDataSource
  request: default-invoke-lambda.req.vtl
  response: default-invoke-lambda.res.vtl
- dataSource: AccessEventLambdaDataSource
  name: InvokeAccessEventLambdaDataSource
  request: default-invoke-lambda.req.vtl
  response: default-invoke-lambda.res.vtl
