name: Deploy Backend (development, develop)

on:
  push:
    branches:
      - develop
    paths:
      - 'serverless/**'
  pull_request:
    branches:
      - develop
    paths:
      - 'serverless/**'

  workflow_dispatch:

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 16.x ]
    defaults:
      run:
        working-directory: serverless

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: serverless/package-lock.json

      - name: Install dependencies
        run: npm install

      - name: Install Serverless
        run: npm i -g serverless@3

      - name: Configure credentials
        run: |
          serverless config credentials \
            --provider aws \
            --profile lcw \
            --key ${{ secrets.AWS_ACCESS_KEY_ID }} \
            --secret ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Validate config by packaging the service
        run: serverless package

      - name: Deploy
        if: ${{ github.event_name == 'push' || github.event_name == 'workflow_dispatch' }}
        run: serverless deploy --stage dev --region us-east-1 --param="bucketSuffix=lcw-dev" --param="appUrl=https://app-stage.letschatwith.com"
